### ISSUE TITLE
Devise 4.7.2 & Omniauth 2.0.3 error: You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed.

### ISSUE THREAD

**Issue by wflanagan** [heartcombo/devise#5354]
I attempted to upgrade my app to the latest Devise and Omniauth. I am tracking master on Omniauth. 

In my bundle update, it updated Omniauth from 1.9.1 to 2.0.3. The Devise version did not change. 

When attempting to run my app again, I got the error described in the title. I have downgraded for now, but I thought you should be aware.

**Comment by carlosantoniodasilva** [comment]
Please use Devise master for now, it contains the necessary fixes to enable OmniAuth 2.x, just wasn't released as a stable version.

Check the [changelog](https://github.com/heartcombo/devise/blob/0cd72a56f984a7ff089246f87a8b259120545edd/CHANGELOG.md#unreleased) for more info.

Thanks.

**Comment by muhammadyana** [comment]
Hello i get same error, i have update my devise gem into branch master but it still error 
```DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from <main> at /Users/user/myapp/config/application.rb:21)```

this is my gemfile
```ruby
gem 'devise', :github => 'heartcombo/devise', :branch => 'master'
gem 'devise_invitable', '~> 2.0.0'
gem 'devise_token_auth'
```

is there any solutions?
Thanks

**Comment by carlosantoniodasilva** [comment]
@muhammadyana that's just a deprecation of another constant in Devise that is on master, and it looks like `devise_token_auth` will need to be updated to accommodate for that eventually: https://github.com/lynndylanhurley/devise_token_auth/issues/1474 and https://github.com/lynndylanhurley/devise_token_auth/pull/1473

**Comment by olbrich** [comment]
@carlosantoniodasilva Can we get the fix for the omniauth change on master released in an actual gem version soon?  Even it that's the only change.

**Comment by carlosantoniodasilva** [comment]
@olbrich at this point I'd consider harder to release just that change separately since it's already on master with a few others. That being said, I will probably go ahead and release master at some point soon since I haven't been able to look at other stuff I wanted to anyway.

You should have no problem using devise master in the meantime, though.

**Comment by carlosantoniodasilva** [comment]
I just pushed v4.8 including this change, please give it a try and report back if you have any issues. Thanks.

**Comment by shqear93** [comment]
I'm still having this issue, this temporary solution worked for me

`gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth', branch: 'master'`

https://github.com/lynndylanhurley/devise_token_auth/issues/1474#issuecomment-860803568

**Comment by michaelbina** [comment]
@shqear93's solution worked for me, but following here to find out when its fixed and I can switch back to main repo

**Comment by suung** [comment]
Hi there,

ran into the same issue, is this fixed now?
